services:
  - type: web
    name: aplikasi-parkir
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Aplikasi Parkir
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://aplikasi-parkir.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: aplikasi-parkir-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: aplikasi-parkir-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: aplikasi-parkir-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: aplikasi-parkir-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: aplikasi-parkir-db
          property: password
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error

databases:
  - name: aplikasi-parkir-db
    databaseName: db_aplikasi_parkir
    user: parkir_user
    plan: free
